"""add must_change_password

Revision ID: 032db4ff37f6
Revises: 85ca84890991
Create Date: 2026-03-19 02:23:18.308366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032db4ff37f6'
down_revision = '85ca84890991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infirmier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    with op.batch_alter_table('medecin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medecin', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('infirmier', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
