"""init

Revision ID: 85ca84890991
Revises: 
Create Date: 2026-03-19 02:07:45.851667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85ca84890991'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('nom_admin', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_admin')
    )
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.alter_column('date_consult',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('motif',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('id_eleve',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('poids',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('taille',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tension',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.alter_column('nom_eleve',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('prenom_eleve',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('classe',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('sexe',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               nullable=False)
        batch_op.alter_column('date_naissance',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('infirmier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('nom_infirmier',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('prenom_infirmier')

    with op.batch_alter_table('medecin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('nom_medecin',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('prenom_medecin')

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('medicament',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('dosage',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('duree',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('id_consult',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.alter_column('id_eleve',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_rdv',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('id_medecin',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rdv', schema=None) as batch_op:
        batch_op.alter_column('id_medecin',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_rdv',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('id_eleve',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('id_consult',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('duree',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('dosage',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('medicament',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('medecin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom_medecin', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('nom_medecin',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('infirmier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom_infirmier', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('nom_infirmier',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.alter_column('date_naissance',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('sexe',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               nullable=True)
        batch_op.alter_column('classe',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('prenom_eleve',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nom_eleve',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.alter_column('tension',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('taille',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('poids',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('id_eleve',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('motif',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('date_consult',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.drop_table('admin')
    # ### end Alembic commands ###
